services:
  app:
    build: .
    container_name: event-management-app
    ports:
      - "3000:3000"
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules